# this job reads informations from temperature sensors
# every minute for 20 times
# ---- MINUTE 1 ----
label=TEMP1
command=TEMP
[NEW]
label=CURR1
command=CURR
[NEW]
label=SLEEP1
command=SLEEP
duration=60
# ---- MINUTE 2 ----
[NEW]
label=TEMP2
command=TEMP
[NEW]
label=CURR2
command=CURR
[NEW]
label=SLEEP2
command=SLEEP
duration=60
# ---- MINUTE 3 ----
[NEW]
label=TEMP3
command=TEMP
[NEW]
label=CURR3
command=CURR
[NEW]
label=SLEEP3
command=SLEEP
duration=60
# ---- MINUTE 4 ----
[NEW]
label=TEMP4
command=TEMP
[NEW]
label=CURR4
command=CURR
[NEW]
label=SLEEP4
command=SLEEP
duration=60
# ---- MINUTE 5 ----
[NEW]
label=TEMP5
command=TEMP
[NEW]
label=CURR5
command=CURR
[NEW]
label=CAL5
command=CAL
mode=NORMAL
write=TRUE
trigger=TRUE
hold_delay=6.6
destination=TEMP1
counter=150
# the calibration will costs about one minute
# so no sleep is needed
